print ("Vamos a hacer arepas")
print ("que ingredientes necesitamos? ")
ingrediente_1= input("ingrediente 1: ")
ingrediente_2= input("ingrediente 2: ")
ingrediente_3= input("ingrediente 3: ")
ingrediente_4= input("ingrediente 4: ")
print ("Colocar las siguientes cantidades en tazas")
cantidad_1= float(input("Cuantas tazas de "+ ingrediente_1 + " necesitamos? "))
cantidad_2= float(input("Cuantas tazas de "+ ingrediente_2 + " necesitamos? "))
cantidad_3= float(input("Cuantas tazas de "+ ingrediente_3 + " necesitamos? "))
cantidad_4= float(input("Cuantas tazas de "+ ingrediente_4 + " necesitamos? "))
arepa= (cantidad_1 + cantidad_2 + cantidad_3 + cantidad_4)
print ("La cantidad total de ingredientes es ", arepa)